name = "px4"
tags = ["px4", "drone"]
component_paths = [
    "Tools/sitl_gazebo/gazebo-component",
    "src/lib/battery/battery-component",
    "src/modules/land_detector/land-detector-component",
    "src/lib/drivers/gyroscope/gyroscope-component",
    "src/modules/commander/commander-component",
    "src/modules/sensors/vehicle_imu/vehicle-imu-component",
    "src/modules/sensors/sensors-component",
    "src/modules/ekf2/ekf2-component",
]
